module.exports = [
  {week:1,
    english:"# Easter (April 7-13) - PRIMAVERA\n\nWhen out of world-wide spaces\nThe sun speaks to the human mind,\nAnd gladness from the depths of soul\nBecomes, in seeing, one with light,\nThen rising from the sheath of self,\nThoughts soar to distances of space\nAnd dimly bind\nThe human being to the spirit's life.",
    italian:"# Atmosfera di Pasqua (7-13 Aprile)\n\nQuando da spazi universali il sole\nparla al senso dell'uomo\ne dal fondo dell'anima alla luce\nla gioia, contemplando, si congiunge,\nallor dal chiuso dell'egoità\nmigran pensieri nei lontani spazi\ne ottusamente avvincono\nallo spirito l'essere dell'uomo.",
    deutsch:"# Osterstimmung (7-13 April)\n\nWenn aus den Weltenweiten\nDie Sonne spricht zum Menschensinn\nUnd Freude aus den Seelentiefen\nDem Licht sich eint im Schauen,\nDann ziehen aus der Selbstheit Hülle\nGedanken in die Raumesfernen\nUnd binden dumpf\nDes Menschen Wesen an des Geistes Sein.",
    refweek: 52,
    Eurythmy: "A"},
  {week:2,
    english:"# Second Week (April 14-20)\n\nOut in the sense-world's glory\nThe power of thought gives up\nits separate being,\nAnd spirit worlds discover\nAgain their human offspring,\nWho germinates in them\nBut in itself must find\nThe fruit of soul.",
    italian:"# Seconda Settimana (14-20 Aprile)\n\nLà fuori, nel sensibile universo,\nsi smarrisce la forza del pensiero;\ni mondi dello spirito\nil rampollo ritrovano dell'uomo,\nche in essi il germe suo,\nma dell'anima il frutto\nin sé deve trovare.",
    deutsch:"# Zweite April-Woche (7.-13.April)\n\nIns Äußre des Sinnesalls\nVerliert Gedankenmacht ihr Eigensein;\nEs finden Geisteswelten\nDen Menschensprossen wieder,\nDer seinen Keim in ihnen,\nDoch seine Seelenfrucht\nIn sich muß finden.",
    refweek: 51,
    Eurythmy: "B"},
  {week:3,
    english:"# Third Week (April 21-27)\n\nThus to the World-All speaks,\nIn self-forgetfulness\nAnd mindful of its primal state,\nThe growing human I:\nIn you, if I can free myself\nFrom fetters of my selfhood,\nI fathom my essential being.",
    italian:"# Terza Settimana (21-27 Aprile)\n\nAll'universo parla, dimentico di sé\ne del suo stato originario memore,\ncrescendo l'io dell'uomo:\nin te, sciogliendomi dai ceppi\ndi ciò che mi è particolare, scopro\nil vero essere mio.",
    deutsch:"# Dritte und vierte April-Woche (14.-24. April)\n\nEs spricht zum Weltenall,\nSich selbst vergessend\nUnd seines Urstands eingedenk,\nDes Menschen wachsend Ich:\nIn dir, befreiend mich\nAus meiner Eigenheiten Fessel,\nErgründe ich mein echtes Wesen.",
    refweek: 50,
    Eurythmy: "C"},
  {week:4,
    english:"# Fourth Week (April 28-May 4)\n\nI sense a kindred nature to my own:\nThus speaks perceptive feeling\nAs in the sun-illuminated world\nIt merges with the floods of light;\nTo thinking's clarity\nMy feeling would give warmth\nAnd firmly bind as one\nThe human being and the world.",
    italian:"# Quarta settimana (28 Aprile - 4 Maggio)\n\nIo sento l'entità dell'esser mio:\ncosì mi parla il senso\nche nel mondo dal sole illuminato\nai fiotti della luce si coingiunge;\nvuole al pensiero\noltre alla chiarità donar calore\ne uomo e mondo\navvincer strettamente in unità.",
    deutsch:"# Vierte April-Woche bis erste Mai-Woche (25. April-4. Mai)\n\nIch fühle Wesen meines Wesens: \nSo spricht Empfindung,\nDie in der sonnerhellten Welt \nMit Lichtesfluten sich vereint; \nSie will dem Denken \nZur Klarheit Wärme schenken \nUnd Mensch und Welt \nIn Einheit fest verbinden.",
    refweek: 49,
    Eurythmy: "D"},
  {week:5,
    english:"# Fifth Week (May 5-11)\n\nWithin the light that out of spirit depths\nWeaves germinating power into space\nAnd manifests the gods' creative work:\nWithin its shine, the soul's true being\nIs widened into worldwide life\nAnd resurrected\nFrom narrow selfhood's inner power.",
    italian:"# Quinta settimana\n\nEntro la luce\nche da profondità spirituali\ncol lavorio fecondo nello spazio\nmanifesta il creare degli dèi,\nora l'anima appare\na vita uniiversale dilatata\ne dalla chiusa forza\nrisorta dell'angusta egoità.",
    deutsch:"# Erste Mai-Woche (5.-11. Mai)\n\nIm Lichte, das aus Geistestiefen \nIm Raume fruchtbar webend \nDer Götter Schaffen offenbart: \nIn ihm erscheint der Seele Wesen \nGeweitet zu dem Weltensein \nUnd auferstanden \nAus enger Selbstheit Innenmacht.",
    refweek: 48,
    Eurythmy: "E"},
  {week:6,
    english:"# Sixth Week (May 12-18)\n\nThere has arisen from its narrow limits\nMy self and finds itself\nAs revelation of all worlds\nWithin the sway of time and space;\nThe world, as archetype divine,\nDisplays to me at every turn\nThe truth of my own likeness.",
    italian:"# Sesta settimana \n\nDa vita singola è il mio sé risorto\ned entro all'universo or si palesa\nnelle forze del tempo e dello spazio;\nin ogni luogo il mondo mi rivela\n - l'archetipo divino -\ndell'immagine mia la verità.",
    deutsch:"# Zweite Mai-Woche (12.-18.Mai)\n\nEs ist erstanden aus der Eigenheit\nMein Selbst und findet sich\nAls Weltenoffenbarung\nIn Zeit- und Raumeskräften;\nDie Welt, sie zeigt mir überall\nAls göttlich Urbild\nDes eignen Abbilds Wahrheit",
    refweek: 47,
    Eurythmy: "F"},
  {week:7,
    english:"# Seventh Week (May 19-25)\n\nMy self is threatening to fly forth,\nLured strongly by the world's enticing light.\nCome forth, prophetic feeling,\nTake up with strength your rightful task:\nReplace in me the power of thought\nWhich in the senses' glory\nWould gladly lose itself.",
    italian:"# Settima settimana (19 Maggio - 25 Maggio)\n\nIl sé minanccia di sfuggiarmi\nda immensa luce ardentemente attratto.\nOr entra, mio presagio,\ncon ogni potestà nei tuoi diritti,\nsuppliscimi la forza del pensiero\nche dai sensi abbagliato\nse stessso perder vuole.",
    deutsch:"# Dritte Mai-Woche (19.-25.Mai)\n\nMein Selbst, es drohet zu entfliehen, \nVom Weltenlichte mächtig angezogen. \nNun trete du mein Ahnen \nIn deine Rechte kräftig ein, \nErsetze mir des Denkens Macht, \nDas in der Sinne Schein \nSich selbst verlieren will.",
    refweek: 46,
    Eurythmy: "G"},
  {week:8,
    english:"# Eighth Week (May 26-June 1)\n\nThe senses' might grows strong \nUnited with the gods' creative work;\nIt presses down my power of thinking\nInto a dreamlike dullness.\nWhen godly being\nDesires union with my soul,\nMust human thinking\nIn quiet dream-life rest content.",
    italian:"# Ottava settimana (26 Maggio - 1 Giugno)\n\nOr s'accresce dei sensi la potenza\nin lega col creare degli dèi;\nla forza del pensiero\na ottuso sogno mi riduce.\nSe natura divina\nvuole al mio cuore unirsi,\numilmente l'umano mio pensiero\ndeve a vita sognante ritirarsi.",
    deutsch:"# Vierte Mai-Woche (20.-31.Mai)\n\nEs wächst der Sinne Macht\nIm Bunde mit der Götter Schaffen,\nSie drückt des Denkens Kraft\nZur Traumes Dumpfheit mir herab.\nWenn göttlich Wesen\nSich meiner Seele einen will,\nMuß menschlich Denken\nIm Traumessein sich still bescheiden.",
    refweek: 45,
    Eurythmy: "H"},
  {week:9,
    english:"# Ninth Week (June 2-8)\n\nWhen I forget the narrow will of self,\nThe cosmic warmth that heralds summer's glory\nFills all my soul and spirit;\nTo lose myself in light\nIs the command of spirit vision\nAnd intuition tells me strongly:\nO lose yourself to find yourself.",
    deutsch:"# Erste Juni-Woche (1.-8. Juni)\n\nVergessend meine Willenseigenheit, \nErfüllet Weltenwärme sommerkündend \nMir Geist und Seelenwesen; \nIm Licht mich zu verlieren \nGebietet mir das Geistesschauen, \nUnd kraftvoll kündet Ahnung mir: \nVerliere dich, um dich zu finden.",
    italian:"# Nona settimana (Giugno 2-8)\n\nNunzio d'estate un cosmico calore\ndel mio volere immemore\nor lo spirito e l'anima mi colma;\nsmarrirmi nella luce\nm'impone l'occhio mio spirituale\ne possente m'annuncia il mio presagio\nperder tidevi, per trovar te stesso.",
    refweek: 44,
    Eurythmy: "I"},
  {week:10,
    english:"# Tenth Week (June 9-15)\n\nTo summer's radiant heights\nThe sun in shining majesty ascends;\nIt takes my human feeling\nInto its own wide realms of space.\nWithin my inner being stirs\nPresentiment which heralds dimly,\nYou shall in future know:\nA godly being now has touched you.",
    italian:"# Decima settimana (Giugno 9-15)\n\nA estive altezze\nlucente s'alza l'essere del sole,\ne il mio sentiero umano\nporta con sé nei suoi remoti spazi;\ns'agita in me preago\nun senso e ottuso annuncia:\nun gioro tu saprai\nche or t'ha sentito un essere divino.",
    deutsch:"# Zweite Juni-Woche (9.-15. Juni)\n\nZu sommerlichen HöhenErhebt der Sonne leuchtend Wesen sich; \nEs nimmt mein menschlich Fühlen \nIn seine Raumesweiten mit. \nErahnend regt im Innern sich \nEmpfindung, dumpf mir kündend, \nErkennen wirst du einst: \nDich fühlte jetzt ein Gotteswesen.",
    refweek: 43,
    Eurythmy: "K"},
  {week:11,
    english:"# Eleventh Week (June 16-23)\n\nIn this the sun's high hour it rests\nWith you to understand these words of wisdom:\nSurrender to the beauty of the world,\nBe stirred with new-enlivened feeling;\nThe human I can lose itself\nAnd find itself within the cosmic I.",
    italian:"# Undicesima settimana (Giugno 16-23)\n\nIn quest'ora solare a te s'addice\nd'interpretare il saggio ammonimento:\ndel mondo alla bellezza abbondonato,\nin te sentendo te sperimentare:\npuò l'io dell'uomo perdersi\ne ritrovarsi dentro l'io del mondo.",
    deutsch:"# Dritte Juni-Woche (16.-22.Juni)\n\nEs ist in dieser Sonnenstunde \nAn dir, die weise Kunde zu erkennen: \nAn Weltenschönheit hingegeben, \nIn dir dich fühlend zu durchleben: \nVerlieren kann das Menschen-Ich \nUnd finden sich im Welten-Ich.",
    refweek: 42,
    Eurythmy: "L"},
  {week:12,
    english:"# St. John's Tide (June 24)\n\nThe radiant beauty of the world\nCompels my inmost soul to free\nGod-given powers of my nature\nThat they may soar into the cosmos,\nTo take wing from myself\nAnd trustingly to seek myself\nIn cosmic light and cosmic warmth.",
    italian:"# Atmosfera di San Giovanni (25 giugno)\n\nLo splendore lucente del creato\ndal profondo del cuor mi costringe\na dar libero volo\ndella mia vita alle divine forze;\na abbandonar me stesso\neppur fidente a ricercarmi\nnella luce e nel calore del mondo.",
    deutsch:"# Johanni-Stimmung (23.-29. Juni)\n\nDer Welten Schönheitsglanz, \nEr zwinget mich aus Seelentiefen \nDes Eigenlebens Götterkräfte \nZum Weltenfluge zu entbinden; \nMich selber zu verlassen, \nVertrauend nur mich suchend \nIn Weltenlicht und Weltenwärme.",
    refweek: 41,
    Eurythmy: "M"},
  {week:13,
    english:"# Thirteenth Week (June 30-July 6)\n\nAnd when I live in senses' heights,\nThere flames up deep within my soul\nOut of the spirit's fiery worlds\nThe gods' own word of truth:\nIn spirit sources seek expectantly\nTo find your spirit kinship.",
    italian:"# Tedicesima settimana\n\nE quando sono all'apice dei sensi\nfiammeggia in fondo al cuore\nda mondi dello spirito infocati\nil mondo dvino:\npresago cerca nel profondo spirito\nallo spirito affine di trovarti.",
    deutsch:"# Fünfte Juni-Woche bis erste Juli-Woche\n\nUnd bin ich in den Sinneshöhen, So flammt in meinen Seelentiefen \nAus Geistes Feuerwelten \nDer Götter Wahrheitswort: \nIn Geistesgründen suche ahnend \nDich geistverwandt zu finden.",
    refweek: 40,
    Eurythmy: "M"},
  {week:14,
    english:"# SUMMER Fourteenth Week (July 7-13)\n\nSurrendering to senses' revelation\nI lost the drive of my own being,\nAnd dreamlike thinking seemed\nTo daze and rob me of myself.\nYet quickening there draws near\nIn sense appearance cosmic thinking.",
    italian:"# ESTATE Quattordicesima settimana\n\nAl messaggio dei sensi m'abbandono,\ndell'esser mio lo stimolo ho perduto\nil sogno dei pensieri\npar che m'abbagli e mi rapisca il sé;\npur già, risvegliatore, a me s'accosta\nnell'illusione il cosmico pensiero.",
    deutsch:"# SOMMER Erste Juli-Woche\n\nAn Sinnesoffenbarung hingegeben\nVerlor ich Eigenwesens Trieb,\nGedankentraum, er schien\nBetäubend mir das Selbst zu rauben,\nDoch weckend nahet schon\nIm Sinnenschein mir Weltendenken.",
    refweek: 39,
    Eurythmy: "N"},
  {week:15, english:"# Fifteenth Week (July 14-20)\n\nI feel enchanted weaving\nOf spirit within outer glory.\nIn dullness of the senses\nIt has enwrapt my being\nIn order to bestow the strength\nWhich in its narrow bounds my I\nIs powerless to give itself.",
            italian:"#Quindicesima settimana\nCome incantato dentro le parvenze\ndello spirito io sento il lavorio;\nha nell'ottusità dei sensi avvolto\nla mia propria entità,\nper domarmi la forza\nche a se stessa d'infondere è impotente\nentro i limiti suoi l'egoità.",
            deutsch:"Ich fühle wie verzaubert\nIm Weltenschein des Geistes Weben:\nEs hat in Sinnesdumpfheit\nGehüllt mein Eigenwesen,\nZu schenken mir die Kraft:\nDie, ohnmächtig sich selbst zu geben,\nMein Ich in seinen Schranken ist.",
            refweek: 38,
            Eurythmy: "O"},
  {week:16,
    english:"# Sixteenth Week (July 21-27)\n\nTo bear in inward keeping spirit bounty\nIs stern command of my prophetic feeling,\nThat ripened gifts divine\nMaturing in the depths of soul\nTo selfhood bring their fruits.",
    italian:"# Sedicesima settimana (21 luglio - 27 luglio)\n\nD'accogliere m'impone il mio presagio\nentro me stesso il dono dello spirito,\na che germi divini si maturino\nnel terreno dell'anima, fecondi,\nfruttificando per l'egoità.",
    deutsch:"# Dritte Juli-Woche (21.-27. Juli)\n\nZu bergen Geistgeschenk im Innern,\n Gebietet strenge mir mein Ahnen, \nDaß reifend Gottesgaben \nIn Seelengründen fruchtend \nDer Selbstheit Früchte bringen.",
    refweek: 37,
    Eurythmy: "P"},
  {week:17,
    english:"# Seventeenth Week (July 28-August 3)\n\nThus speaks the cosmic Word\nThat I by grace through senses' portals\nHave led into my innermost soul:\nImbue your spirit depths\nWith my wide world horizons\nTo find in future time myself in you.",
    italian:"## Diciassettesima settimana (28 Luglio - 3 Agosto)\n\nM'annuncia il verbo universale\nche attraverso i miei sensi\nnei recessi del cuor potei guidare:\ndello spirito tuo colma gli abissi\ncoi miei spazi celesti,\na che tu possa me trovare in te.",
    deutsch:"# Vierte Juli-Woche (28. Juli-3. August)\n\nEs spricht das Weltenwort, \nDas ich durch Sinnestore \nIn Seelengründe durfte führen: \nErfülle deine Geistestiefen \nMit meinen Weltenweiten, \nZu finden einstens mich in dir.",
    refweek: 36,
    Eurythmy: "Q"},
  {week:18,
    english:"# Eighteenth Week (August 4-10)\n\nCan I expand my soul\nThat it unites itself\nWith cosmic Word received as seed?\nI sense that I must find the strength\nTo fashion worthily my soul\nAs fitting raiment for the spirit.",
    italian:"# Diciottesima settimana (4-10 Agosto)\n\nDilatare potrò l'anima mia\nperché s'unisca al concepito germe\ndel verbo universale?\nIo sento che trovare debbo la forza\nche faccia degna l'anima\ndi modellarsi a veste dello spirito.",
    deutsch:"# Erste August-Woche (4.-10. August)\n\nKann ich die Seele weiten, \nDaß sie sich selbst verbindet \nEmpfangnem Welten-Keimesworte ? \nIch ahne, daß ich Kraft muß finden, \nDie Seele würdig zu gestalten, \nZum Geisteskleide sich zu bilden.",
    refweek: 35,
    Eurythmy: "R"},
  {week:19,
    english:"# Nineteenth Week (August 11-17)  \n\nIn secret to encompass now\nWith memory what I've newly got\nShall be my striving's further aim:\nThus, ever strengthening, selfhood's forces\nShall be awakened from within\nAnd growing, give me to myself.",
    italian:"# Diciannovesima settimana (11-17 Agosto)\n\nSegretamente il concepito germe\ncol ricordo abbracciare,\nil senso or sia dell'anelare mio:\ndestare deve le mie proprie forze\ne accrescerle entro me,\ne dare divenendo me a me stesso.",
    deutsch:"# Zweite August-Woche (11.-17. August)\n\nGeheimnisvoll das Neu-Empfang'ne \nMit der Erinn'rung zu umschließen, \nSei meines Strebens weitrer Sinn: \nEr soll erstarkend Eigenkräfte \nIn meinem Innern wecken \nUnd werdend mich mir selber geben.",
    refweek: 34,
    Eurythmy: "S"},
  {week:20,
    english:"# Twentieth Week (August 18-24)\n\nI feel at last my life's reality\nWhich, severed from the world's existence,\nWould in itself obliterate itself,\nAnd building only on its own foundation,\nWould in itself bring death upon itself.",
    italian:"# Ventesima settimana (18-24 Agosto)\n\nCosì soltanto io sento l'esser mio:\ndall'esistenza cosmica lontano,\nin sé se stesso estinguere dovrebbe;\nesolo su se stesso edificando,\nin sé se stesso uccidere.",
    deutsch:"# Dritte August-Woche (18.-24. August)\n\nSo fühl ich erst mein Sein,\nDas fern vom Welten-Dasein\nIn sich sich selbst erlöschen\nUnd bauend nur auf eignem Grunde\nIn sich sich selbst ertöten müßte.",
    refweek: 33,
    Eurythmy: "T"},
  {week:21,
    english:"# Twenty-first Week (August 25-31)\n\nI feel strange power, bearing fruit\nAnd gaining strength to give myself to me.\nI sense the seed maturing\nAnd expectation, light-filled, weaving\nWithin me on my selfhood's power.",
    italian:"# Ventunesima settimana (25-31 Agosto)\n\nFeconda io sento una potenza ignota\nche, crescendo, me stesso a me concede;\nio maturarsi il germe avverto\ned un presagio luminosamente\nnell'intimo operare\nsulla potenza dell'egoità.",
    deutsch:"# Vierte August-Woche (25.-31.August)\n\nIch fühle fruchtend fremde Macht\nSich stärkend mir mich selbst verleihn, \nDen Keim empfind ich reifend \nUnd Ahnung lichtvoll weben \nIm Innern an der Selbstheit Macht.",
    refweek: 32,
    Eurythmy: "U"},
  {week:22,
    english:"# Twenty-second Week (September 1-7)\n\nThe light from world-wide spaces\nWorks on within with living power;\nTransformed to light of soul\nIt shines into the spirit depths\nTo bring to birth the fruits\nWhereby out of the self of worlds\nThe human self in course of time shall ripen.",
    italian:"# Ventiduesima settimana (1-7 Settembre)\n\nDa lontananze cosmiche, possente,\nin me continua a vivere la luce;\ndiventa luce d'anima\ned in fondo allo spritio risplende,\nper generarne frutti\nche faccian nel futuro maturare\ndall'io del mondo l'io dell'uomo.",
    deutsch:"# Erste September-Woche (1.-7. September)\n\nDas Licht aus Weltenweiten, \nIm Innern lebt es kräftig fort: \nEs wird zum Seelenlichte \nUnd leuchtet in die Geistestiefen,\nUm Früchte zu entbinden,\nDie Menschenselbst aus Weltenselbst \nIm Zeitenlaufe reifen lassen.",
    refweek: 31,
    Eurythmy: "V"},
  {week:23,
    english:"# Twenty-third Week (September 8-14)  \n\nThere dims in damp autumnal air\nThe senses' luring magic;\nThe light's revealing radiance\nIs dulled by hazy veils of mist.\nIn distances around me I can see\nThe autumn's winter sleep;\nThe summer's life has yielded\nItself into my keeping.",
    italian:"# Ventitreesima settimana (8-1 Settembre)\n\nSi spegne autunnalmente\ndegli anelanti sensi l malìa,\nsimischiano alla luce\ni cupi veli della nebbia.\nIo stesso negli spazi\nguardo al sonno cosmico dell'autunno.\nL'estate m0ha donato\ntutta se stessa.",
    deutsch:"# Zweite September-Woche (8.-14. September)\n\nEs dämpfet herbstlich sich \nDer Sinne Reizesstreben; \nIn Lichtesoffenbarung mischen \nDer Nebel dumpfe Schleier sich. \nIch selber schau in Raumesweiten \nDes Herbstes Winterschlaf. \nDer Sommer hat an mich \nSich selber hingegeben.",
    refweek: 30,
    Eurythmy: "W"},
  {week:24,
    english:"# Twenty-fourth Week (September 15-21)\n\nUnceasingly itself creating\nSoul life becomes aware of self;\nThe cosmic spirit, striving on,\nRenews itself by self-cognition,\nAnd from the darkness of the soul\nCreates the fruit of self-engendered will.",
    italian:"# Ventiquattresima settimana (15-21 Settembre)\n\nSe stessa edificando senza posan\nl'anima di se stessa ora s'avvede;\ndel mondo l'io perpetuamente anela\nnel conoscer se stesso ravvivato,\ne dal buio dell'anima\n - frutto di volontà -\nil sentimento di se stesso crea.",
    deutsch:"# Dritte September-Woche (15 .-21. September)\n\nSich selbst erschaffend stets,\nWird Seelensein sich selbst gewahr; \nDer Weltengeist, er strebet fort \nIn Selbsterkenntnis neu belebt \nUnd schafft aus Seelenfinsternis \nDes Selbstsinns Willensfrucht.",
    refweek: 29,
    Eurythmy: "X"},
  {week:25,
    english:"# Twenty-fifth Week (September 22-28)\n\nI can belong now to myself\nAnd shining spread my inner light\nInto the dark of space and time.\nToward sleep is urging all creation,\nBut inmost soul must stay awake\nAnd carry wakefully sun's glowing\nInto the winter's icy flowing.",
    italian:"# Venticinquesima settimana (22-28 Settembre)\n\nOr posso appartenermi\ne effondere splendendo luce mia\nentro il buio del tempo e dello spazio.\nAd assopirsi tende la natura;\nhan da vegliar dell'anima gli abissi\ne desti han da portare sole ardente\nnel gelo dell'inverno.",
    deutsch:"# Vierte September-Woche (22.-28. September)\n\nIch darf nun mir gehören\nUnd leuchtend breiten Innenlicht \nIn Raumes- und in Zeitenfinsternis. \nZum Schlafe drängt natürlich Wesen, \nDer Seele Tiefen sollen wachen \nUnd wachend tragen Sonnengluten \nIn kalte Winterfluten.",
    refweek: 28,
    Eurythmy:"Y"},
  {week:26,
    english:"# Michaelmas (September 29-October 5)  \n\nO Nature, your maternal life\nI bear within the essence of my will.\nAnd my will's fiery energy\nShall steel my spirit striving,\nThat sense of self springs forth from it\nTo hold me in myself.",
    italian:"# Atmosfera di San Michele\n\nO natura, la tua maternità,\nio la porto entro me nel mio volere;\ne del volere l'infocata forza\ngli impulsi miei spirituali tempra,\nil sentimento a generar del sé,\nche porti me in me stesso.",
    deutsch:"# Michaeli-Stimmung\n\nNatur, dein mütterliches Sein,\nIch trage es in meinem Willenswesen; \nUnd meines Willens Feuermacht, \nSie stählet meines Geistes Triebe, \nDaß sie gebären Selbstgefühl \nZu tragen mich in mir.",
    refweek: 27,
    Eurythmy:"Z"},
  {week:27,
    english:"# Twenty-seventh Week (October 6-12)\nAUTUMN\n\nWhen to my being's depths I penetrate,\nThere stirs expectant longing\nThat self-observing, I may find myself\nAs gift of summer sun, a seed\nThat warming lives in autumn mood\nAs germinating force of soul.",
    italian:"# Ventisettesima settimana (6-12 Ottobre)\nAUTUNNO\n\nDell'esser mio nel fondo penetrare\ndesta un presago anelito:\nch'io, contemplando me, me stesso trovi\n- solare dono dell'estate che\nnell'aria autunnalein germe cova -\nqual sorgente di forze del mio cuore.",
    deutsch:"# Erste Oktober-Woche (6.-12. Oktober)\nHERBST\n\nIn meines Wesens Tiefen dringen: \nErregt ein ahnungsvolles Sehnen, \nDaß ich mich selbstbetrachtend finde, \nAls Sommersonnengabe, die als Keim \nIn Herbstesstimmung wärmend lebt \nAls meiner Seele Kräftetrieb.",
    refweek: 26,
    Eurythmy:"A"},
  {week:28,
    english:"# Twenty-eighth Week (October 13-19)  \n\nI can, in newly quickened inner life,\nSense wide horizons in myself.\nThe force and radiance of my thought —\nComing from soul's sun power —\nCan solve the mysteries of life,\nAnd grant fulfillment now to wishes\nWhose wings have long been lamed by hope.",
    italian:"# Ventottesima settimana (13-19 Ottobre)\n\nIo posso entro di me vivificato\nsentir le immensità dell'esser mio\ne vigorosa luce di pensiero\ncon la forza solare del mio cuore\neffonder sugli enigmi della vita,\nsciogliendoli, e appagare desideri\ncui la speranza già tarpava l'ali.",
    deutsch:"# Zweite Oktober-Woche (13.-19. Oktober)\n\nIch kann im Innern neu belebt \nErfühlen eignen Wesens Weiten \nUnd krafterfüllt Gedankenstrahlen \nAus Seelensonnenmacht \nDen Lebensrätseln lösend spenden, \nErfüllung manchem Wunsche leihen, \nDem Hoffnung schon die Schwingen lähmte.",
    refweek: 25,
    Eurythmy: "B"},
  {week:29,
    english:"# Twenty-ninth Week (October 20-26)\n\nTo fan the spark of thinking into flame\nBy my own strong endeavor,\nTo read life's inner meaning\nOut of the cosmic spirit's fount of strength:\nThis is my summer heritage,\nMy autumn solace, and my winter hope.",
    italian:"# Ventinovesima settimana (20-26 Ottobre)\n\nAccendere a se stessi dentro sé\nfortemente la luce del pensiero,\ndella vita il profondo senso attingere\nalle fonti di forza dello spirito,\nm'è dell'estate eredità,\npace d'autunno e speranza invernale.",
    deutsch:"# Dritte Oktober-Woche (20.-26.Oktober)\n\nSich selbst des Denkens Leuchten\nIm Innern kraftvoll zu entfachen,\nErlebtes sinnvoll deutend\nAus Weltengeistes Kräftequell,\nIst mir nun Sommererbe,\nIst Herbstesruhe und auch Winterhoffnung.",
    refweek: 24,
    Eurythmy: "C"},
  {week:30,
    english:"Thirtieth Week (October 27-November 2)\n\nThere flourish in the sunlight of my soul\nThe ripened fruits of thinking;\nTo conscious self-assurance\nThe flow of feeling is transformed.\nI can perceive now joyfully\nThe autumn's spirit-waking:\nThe winter will arouse in men\The summer of the soul.",
    italian:"# Trentesima settimana (27 Ottobre - 2 Novembre)\n\nDell'anima nel chiaro sole\nmi maturano i frutti del pensiero\nin sicurezza di chi sé conosce\nsi muta ogni sentire.\nAvverto in gran letizia\ndestarsi nello spirito l'autunno:\nl'inverno in me\nrisveglierà dell'anima l'estate.",
    deutsch:"# Vierte Oktober-Woche (27. Oktober-2. November)\n\nEs sprießen mir im Seelensonnenlicht \nDes Denkens reife Früchte, \nIn Selbstbewußtseins Sicherheit \nVerwandelt alles Fühlen sich. \nEmpfinden kann ich freudevoll \nDes Herbstes Geisterwachen: \nDer Winter wird in mir \nDen Seelensommer wecken.",
    refweek: 23,
    Eurythmy: "D"},
  {week:31,
    english:"# Thirty-first Week (November 3-9)\n\nThe light from spirit depths\nStrives to ray outwards, sun-imbued;\nTransformed to forceful will of life\nIt shines into the senses' dullness\nTo bring to birth the powers\nWhereby creative forces, soul-impelled,\nShall ripen into human deeds.",
    italian:"# Trentunesima settimana (3-9 Novembre)\n\nLa luce dei sostrati dello spirito\nad effondersi anela solarmente:\nin volontà di vita si tramuta\ne negli ottusi sensi ora riluce,\nper svincolare forze\nche creatrici potestà da impulsi\ndell'anima nell'opera dell'uomo\nfacciano maturare.",
    deutsch:"# Erste November-Woche (3.-9.November)\n\nDas Licht aus Geistestiefen,\nNach außen strebt es sonnenhaft.\nEs wird zur Lebenswillenskraft\nUnd leuchtet in der Sinne Dumpfheit,\nUm Kräfte zu entbinden,\nDie Schaffensmächte aus Seelentrieben\nIm Menschenwerke reifen lassen.",
    refweek: 22,
    Eurythmy: "E"},
  {week:32,
    english:"# Thirty-second Week (November 10-16)\n\nI feel my own force, bearing fruit\nAnd gaining strength to give me to the world.\nMy inmost being I feel charged with power\nTo turn with clearer insight\nToward the weaving of life's destiny.",
    italian:"# Trentaduesima settimana (10-16 Novembre)\n\nFruttificare io sento la mia forza,\ncorroborarsi e conferirmi al mondo;\nsento l'essere mio che si sustanzia,\nper volgersi alla luce\nentro la trama del destino umano.",
    deutsch:"# Zweite November-Woche (10.-16.November)\n\nIch fühle fruchtend eigne Kraft\nSich stärkend mich der Welt verleihn; \nMein Eigenwesen fühl ich kraftend \nZur Klarheit sich zu wenden \nIm Lebensschicksalsweben.",
    refweek: 21,
    Eurythmy: "F"},
  {week:33,
    english:"Thirty-third Week (November 17-23)\n\nI feel at last the world's reality\nWhich, lacking the communion of my soul,\nWould in itself be frosty, empty life,\nAnd showing itself powerless\nTo recreate itself in souls,\nWould in itself find only death.",
    italian:"# Trentrateesima settimana (17-23 Novembre)\n\nCosì soltanto io sento l'universo:\nsenza il palpito vivo del mio cuore\nin se stesso è sol gelo e vuota vita;\ne se impotente mai si rivelasse\na generarsi a nuovo dentro i cuori,\ntrovar potrebbe in sé sotlanto morte.",
    deutsch:"# Dritte November-Woche (17.-23.November)\n\nSo fühl ich erst die Welt,\nDie außer meiner Seele Miterleben \nAn sich nur frostig leeres Leben \nUnd ohne Macht sich offenbarend, \nIn Seelen sich von neuem schaffend, \nIn sich den Tod nur finden könnte.",
    refweek: 20,
    Eurythmy: "G"},
  {week:34,
    english:"# Thirty-fourth Week (November 24-30)  \n\nIn secret inwardly to feel\nHow all that I've preserved of old\nIs quickened by new-risen sense of self:\nThis shall, awakening, pour forth cosmic forces\nInto the outer actions of my life\nAnd growing, mould me into true existence.",
    italian:"# Trentaquattresima settimana (24-30 Novembre)\n\nSentir segretamente il dono antico\nin sé risorto\ndentro l'intimo mio vivificarsi:\nrisvegliare dovrà cosmiche forze,\nentro l'opera mia dovrà trasfonderle,\ne divenendo\nnell'esistenza me stesso impronare.",
    deutsch:"# Vierte November-Woche (24.-30.November)\n\nGeheimnisvoll das Alt-Bewahrte\nMit neu erstandnem Eigensein\nIm Innern sich belebend fühlen:\nEs soll erweckend Weltenkräfte\nIn meines Lebens Außenwerk ergießen\nUnd werdend mich ins Dasein prägen.",
    refweek: 19,
    Eurythmy: "H"},
  {week:35,
    english:"# Thirty-fifth Week (December 1-7)\n\nCan I know life's reality\nSo that it's found again\nWithin my soul's creative urge?\nI feel that I am granted power\nTo make my self, as humble part,\nAt home within the cosmic self.",
    italian:"# Trentacinquesima settimana (1-7 Dicembre)\n\nRiconoscere l'essere potrò,\nsì ch'esso si ritrovi\nnell'impulso dell'anima a creare?\nIo sento che il potere m'è largito\nd'immergere il mio sé modestamente,\nparte d'un tutto, dentro il sé del mondo.",
    deutsch:"# Erste Dezember-Woche (1.-7.Dezember)\n\nKann ich das Sein erkennen, \nDaß es sich wiederfindet \nIm Seelenschaffensdrange ? \nIch fühle, daß mir Macht verlieh'n, \nDas eigne Selbst dem Weltenselbst \nAls Glied bescheiden einzuleben.",
    refweek: 18,
    Eurythmy: "I"},
  {week:36,
    english:"Thirty-sixth Week (December 8-14)\n\nWithin my being's depths there speaks,\nIntent on revelation,\nThe cosmic Word mysteriously:\nImbue your labor's aims\nWith my bright spirit light\nTo sacrifice yourself through me.",
    italian:"# Trentaseiesima settimana (8-11 Dicembre)\n\nNel profondo dell'esser mio m'annuncia,\ndi rivelarsi anelo,\nsegretamente il verbo universale:\nle mete adempi dell'opera tu\ncol lue mio spirituale,\nper offrire mediante me te stesso.",
    deutsch:"# Zweite Dezember-Woche (8.-14.Dezember)\n\nIn meines Wesens Tiefen spricht \nZur Offenbarung drängend \nGeheimnisvoll das Weltenwort: \nErfülle deiner Arbeit Ziele \nMit meinem Geisteslichte, \nZu opfern dich durch mich.",
    refweek: 17,
    Eurythmy: "K"},
  {week:37,
    english:"# Thirty-seventh Week (December 15-21)\nWINTER\n\nTo carry spirit light into world-winter-night\nMy heart is ardently impelled,\nThat shining seeds of soul\nTake root in grounds of worlds\nAnd Word Divine through senses' darkness\nResounds, transfiguring all life.",
    italian:"# Trentasettesima settimana (18 Dicembre - 21 Dicembre)\n\nINVERNO\nLa luce dello spirito a portare\nnella notte invernale del creato\nbeatamente anela il cuore mio:\na che i germi dell'anima, lcenti,\nfonde radici mettano nel mondo\ne nel buio dei sensi la Parola\nrisonando ogni cosa trasfiguri.",
    deutsch:"# Dritte Dezember-Woche (15.-21.Dezember)\n\nZu tragen Geisteslicht in Weltenwinternacht \nErstrebet selig meines Herzens Trieb, \nDaß leuchtend Seelenkeime \nIn Weltengründen wurzeln, \nUnd Gotteswort im Sinnesdunkel \nVerklärend alles Sein durchtönt.",
    refweek: 16,
    Eurythmy: "L"},
  {week:38,
    english:"# Christmas (December 22-28)\n\nThe spirit child within my soul\nI feel freed of enchantment.\nIn heart-high gladness has\nThe holy cosmic Word engendered\nThe heavenly fruit of hope,\nWhich grows rejoicing into worlds afar\nOut of my being's godly roots.",
    italian:"# Atmosfera di Natale\n\nSento disincantato in grembo all'anima\nil figlio dello spritio;\nil sacrosanto verbo universale\ndel cuore ha generato nella luca\n- frutto celestiale - la speranza\nche dal fondo divino di me stesso\nentro gli spazi giubilando d'alza.",
    deutsch:"# Weihe-Nacht-Stimmung\n\nIch fühle wie entzaubert\nDas Geisteskind im Seelenschoss;\nEs hat in Herzenshelligkeit\nGezeugt das Heilige Weltenwort\nDer Hoffnung Himmelsfrucht,\nDie jubelnd wächst in Weltenfernen\nAus meines Wesens Gottesgrund.",
    refweek: 15,
    Eurythmy: "M"},
  {week:39,
    english:"# Thirty-ninth Week (December 29-January 4)\n\nSurrendering to spirit revelationI gain the light of cosmic being;\nThe power of thinking, growing clearer,\nGains strength to give myself to me,\nAnd quickening there frees itself\nFrom thinker's energy my sense of self.",
    italian:"# Trentanovesima settimana\n\nSe lo sguardo allo spirito rivolgo\nluce dell'ente universale acquisto.\nLa forza del pensiero ora s'accresce\nsé rischiandoper dar me a me stesso;\ne dalla possa del pensiero mio\n- risvegliatore -\nil sentimento del mio sé si leva",
    deutsch:"# Fünfte Dezember-Woche An\n\nGeistesoffenbarung hingegeben\nGewinne ich des Weltenwesens Licht.\nGedankenkraft, sie wächst\nSich klärend mir mich selbst zu geben,\nUnd weckend löst sich mir\nAus Denkermacht das Selbstgefühl.",
    refweek: 14,
    Eurythmy: "N"},
  {week:40,
    english:"# Fortieth Week (January 5-11)\n\nAnd when I live in spirit depths\nAnd dwell within my soul's foundations,\nThere streams from love-worlds of the heart,\nTo fill the vain delusion of the self,\nThe fiery power of the cosmic Word.",
    italian:"# Quarantesima settimana\n\nE quando entro lo spirito m'immergo,\nmi s'empie in fondo all'anima,\ndall'amoroso mondo del mio cuore,\nil vuoto sogno del particolare\ncon la fiamma del verbo universale.",
    deutsch:"# Erste Januar-Woche\n\nUnd bin ich in den Geistestiefen,\nErfüllt in meinen Seelengründen\nAus Herzens Liebewelten\nDer Eigenheiten leerer Wahn\n Sich mit des Weltenwortes Feuerkraft.",
    refweek: 13,
    Eurythmy: "O"},
  {week:41,
    english:"# Forty-first Week (January 12-18)\n\nThe soul's creative might\nStrives outward from the heart's own core\nTo kindle and inflame god-given powers\nIn human life to right activity;\nThe soul thus shapes itself\nIn human loving and in human working.",
    italian:"# Quarantunesima settimana (Gennaio 12-18)\n\nDel cuore la potenza creatrice\nprofondamente anela\nforze divine nella vita umana\nad infiammare per un retto agire,\na plasmare se stessa\nnell'amore e nella opera dell'uomo.",
    deutsch:"# Zweite Januar-Woche\n\nDer Seele Schaffensmacht,\nSie strebet aus dem Herzensgrunde,\nIm Menschenleben Götterkräfte\nZu rechtem Wirken zu entflammen,\nSich selber zu gestalten\nIn Menschenliebe und im Menschenwerke.",
    refweek: 12,
    Eurythmy: "P"},
  {week:42,
    english:"# Forty-second Week (January 19-25)\n\nIn this the shrouding gloom of winterThe soul feels ardently impelled\nTo manifest its innate strength,\nTo guide itself to realms of darkness,\nAnticipating thus\nThrough warmth of heart the sense-world's\nrevelation.\n",
    italian:"# Quarantaduesima settimana (Gennaio 19-25)\n\nIn questo oscuro inverno\nè potente dell'anima l'impulso\na palesare la sua proprietà forza,\nad aprirle un cammino nelle tenebre\ne a presagire col calor del cuore\ndei sensi la rivelazione.",
    deutsch:"# Dritte Januar-Woche (19.-25.Januar)\n\nEs ist in diesem Winterdunkel\nDie Offenbarung eigner Kraft\nDer Seele starker Trieb,\nIn Finsternisse sie zu lenken\nUnd ahnend vorzufühlen,\nDurch Herzenswärme, Sinnesoffenbarung.",
    refweek: 11,
    Eurythmy: "Q"},
  {week:43,
    english:"# Forty-third Week (January 26-February 1)\n\nIn winter's depths is kindled\nTrue spirit life with glowing warmth;\nIt gives to world appearance,\nThrough forces of the heart, the power to be.\nGrown strong, the human soul defies\nWith inner fire the coldness of the world.",
    italian:"# Quaranduesima settimana (26 Gennaio - 1 Febbraio)\n\nNel più profondo inverno\nla spiritualità vera d'accende;\ncon le forze del cuore\nda alla parvenza potestà di vita;\ns'oppone al gelo cosmico e s'accresce\ndell'anima la fiamma dentro l'uomo.",
    deutsch:"# Vierte Januar-Woche (26.Januar-1.Februar)\n\nIn winterlichen Tiefen\nErwarmt des Geistes wahres Sein;\nEs gibt dem Weltenscheine\nDurch Herzenskräfte Daseinsmächte;\nDer Weltenkälte trotzt erstarkend\nDas Seelenfeuer im Menscheninnern.",
    refweek: 10,
    Eurythmy: "R"},
  {week:44,
    english:"# Forty-fourth Week (February 2-8)\n\nIn reaching for new sense attractions,\nSoul-clarity would fill,\nMindful of spirit-birth attained,\nThe world's bewildering, sprouting growth\nWith the creative will of my own thinking. ",
    italian:"# Quarantaquattresima settimana (2-8 Febbraio)\n\nCogliendo nuovi stimoli dei sensi\nla chiarità dell'anima ch'è memore\ndel generato spirito,\nriempie l'universo in divenire,\nin tutto il suo caostico rigoglio,\ncol mio pensiero che a creare anela.",
    deutsch:"# Erste Februar-Woche (2.-8.Februar)\n\nErgreifend neue Sinnesreize \nErfüllet Seelenklarheit, \nEingedenk vollzogner Geistgeburt, \nVerwirrend sprossend Weltenwerden \nMit meines Denkens Schöpferwillen.",
    refweek: 9,
    Eurythmy: "S"},
  {week:45,
    english:"# Forty-fifth Week (February 9-15)\n\nMy power of thought grows firm\nUnited with the spirit's birth.\nIt lifts the senses' dull attractions\nTo bright-lit clarity.\nWhen soul-abundance\nDesires union with the world's becoming,\nMust senses' revelation\nReceive the light of thinking.",
    italian:"# Quantacinquesima settimana (9 Febbraio - 15 Febbraio)\n\nLa forza del pensiero si rinsalda\nal nasce dello spirito congiiunta;\ngli ottusi stimoli dei sensi\nsolleva a chiarità.\nSe la pienezza d'anima\nal divenire vuol del mondo unirsi,\ndei sensi la rivelazione\nla luce deve accoglier del pensiero.",
    deutsch:"# Zweite Februar-Woche (9.-15.Februar)\n\nEs festigt sich Gedankenmacht \nIm Bunde mit der Geistgeburt, \nSie hellt der Sinne dumpfe Reize \nZur vollen Klarheit auf. \nWenn Seelenfülle\nSich mit dem Weltenwerden einen will, \nMuß Sinnesoffenbarung \nDes Denkens Licht empfangen.",
    refweek: 8,
    Eurythmy: "T"},
  {week:46,
    english:"# Forty-sixth Week (February 16-22)\n\nThe world is threatening to stun\nThe inborn forces of my soul;\nNow, memory, come forth\nFrom spirit depths, enkindling light;\nInvigorate my inward sight\nWhich only by the strength of will\nIs able to sustain itself.",
    italian:"# Quantaseiesima settimana (16 Febbraio - 22 Febbraio)\n\nIl mondo ora minaccia di stordire\ndell'anima la forza innata;\nor sorgi tu, ricordo,\ndal fondo dello spritio, splendente,\ne la veggenza accrescimi\nche solo può sussistere\nmercé la forza della volontà.",
    deutsch:"# Dritte Februar-Woche (16. -22.Februar)\n\nDie Welt, sie drohet zu betäuben \nDer Seele eingebor'ne Kraft; \nNun trete du, Erinnerung, \nAus Geistestiefen leuchtend auf \nUnd stärke mir das Schauen, \nDas nur durch Willenskräfte \nSich selbst erhalten kann.",
    refweek: 7,
    Eurythmy: "U"},
  {week:47,
    english:"# Forty-seventh Week (February 23-March 1)\n\nThere will arise out of the world's great womb,\nQuickening the senses' life, the joy of growth.\nNow may it find my strength of thought\nWell armed by powers divine\nWhich strongly live within my being.",
    italian:"# Quarantasettesima settimana ( 23 Febbraio - 1 Marzo)\n\n Risorger vuol dal grembo universale,\ndei sensi ravvivando la parvenza,\ngioia del divenire.\nTrovi il pensiero mio fortificato\ndalle forze divine\nche vigorose vivono entro di me",
    deutsch:"# Vierte Februar-Woche (23.Februar-1.März)\n\nEs will erstehen aus dem Weltenschoße, \nDen Sinnenschein erquickend, Werdelust. \nSie finde meines Denkens Kraft \nGerüstet durch die Gotteskräfte, \nDie kräftig mir im Innern leben.",
    refweek: 6,
    Eurythmy: "V"},
  {week:48,
    english:"# Forty-eighth Week (March 2-8)\n\nWithin the light that out of world-wide heights\nWould stream with power toward the soul,\nMay certainty of cosmic thinking\nArise to solve the soul's enigmas —\nAnd focusing its mighty rays,\nAwaken love in human hearts.",
    italian:"# Quarantottesima settimana (2-8 Marzo)\n\nEntro la luce che possentemente\nvuol dai cieli nell'anima fluire,\nappaia, enigmi d'anima sciogliendo,\nsicurezza del scosmico pensiero\ne dei suoi raggi la potenza aduni \ndestando amore nell'umano cuore",
    deutsch:"# Erste März-Woche (2.-8.März)\n\nIm Lichte, das aus Weltenhöhen\nDer Seele machtvoll fließen will, \nErscheine, lösend Seelenrätsel, \nDes Weltendenkens Sicherheit, \nVersammelnd seiner Strahlen Macht, \nIm Menschenherzen Liebe weckend.",
    refweek: 5,
    Eurythmy: "W"},
  {week:49,
    english:"# Forty-ninth Week (March 9-15)\n\nI feel the force of cosmic life:\nThus speaks my clarity of thought,\nRecalling its own spirit growth\nThrough nights of cosmic darkness,\nAnd to the new approach of cosmic day\nIt turns its inward rays of hope.",
    italian:"# Quarantanovesima settimana (9-15 Marzo)\n\nDell'universo in me sento la forza:\ncosì parla chiarezza di pensiero;\nrammenta del suo spirito il fiorire\nnelle notturne tenebre del mondo,\ne raggi di speranza entro di sé\nprotende al giorno cosmico che viene.",
    deutsch:"# Zweite März-Woche (9.-15.März)\n\nIch fühle Kraft des Weltenseins: \nSo spricht Gedankenklarheit, \nGedenkend eignen Geistes Wachsen \nIn finstern Weltennächten, \nUnd neigt dem nahen Weltentage \nDes Innern Hoffnungsstrahlen.",
    refweek: 4,
    Eurythmy: "X"},
  {week:50,
    english:"# Fiftieth Week (March 16-22)\n\nThus to the human ego speaks\nIn mighty revelation,\nUnfolding its inherent powers,\nThe joy of growth throughout the world:\nI carry into you my life\nFrom its enchanted bondage\nAnd so attain my truest goal.",
    italian:"# Cinquantesima settimana\n\nAll'io dell'uomo parla,\npossente rivelandosi\ne dell'essere suo sciogliendo forze,\ngioiosamente il cosmo in divenire:\ntrasportando entro te la vita mia\ndal magico suo regno,\nla vera meta io attingo.",
    deutsch:"# Dritte März-Woche (16.-20.März)\n\nEs spricht zum Menschen-Ich, \nSich machtvoll offenbarend \nUnd seines Wesens Kräfte lösend, \nDes Weltendaseins Werdelust: \nIn dich mein Leben tragend \nAus seinem Zauberbanne, \nErreiche ich mein wahres Ziel.",
    refweek: 3,
    Eurythmy: "Y"},
  {week:51,
    english:"# Fifty-first Week (March 23-29)\n\nInto our inner being\nThe riches of the senses pour.\nThe Cosmic Spirit finds itself\nReflected in the human eye,\bWhich ever must renew its strength\nFrom out that spirit source.",
    italian:"# Attesa di primavera\n\nEntro l'essere umano si riversa\ndei sensi la dovizia;\nsi rispecchia lo spirito del mondo\nnell'occhio umano,\nche trarn deve la sua forza nuova.",
    deutsch:"# Frühling-Erwartung (21.-25.März)\n\nIns Innre des Menschenwesens \nErgießt der Sinne Reichtum sich, \nEs findet sich der Weltengeist Im Spiegelbild des Menschenauges,\nDas seine Kraft aus ihm \nSich neu erschaffen muß.",
    refweek: 2,
    Eurythmy: ""},
  {week:52,
    english:"# Fifty-second Week (March 30)\n\nWhen from the depths of soul\nThe spirit turns to the life of worlds\nAnd beauty wells from wide expanses,\nThen out of heaven's distances\nStreams life-strength into human bodies,\nUniting by its mighty energy\nThe spirit's being with our human life.",
    italian:"# Cinquantaduesima settimana (30 Marzo)\n\nSe dal fondo dell'anima\nlo spirito si volge all'universo\ne bellezza fluisce dagli spazi,\nallor si versa da remoti cieli\nforza di vita negli umani corpi\ned operando con potenza unisce\nl'essenza dello spirito dell'uomo.",
    deutsch:"# Fünfte März-Woche\n\nWenn aus den Seelentiefen\nDer Geist sich wendet zu dem Weltensein\nUnd Schönheit quillt aus Raumesweiten,\nDann zieht aus Himmelsfernen\nDes Lebens Kraft in Menschenleiber\nUnd einet, machtvoll wirkend,\nDes Geistes Wesen mit dem Menschensein.",
    refweek: 1,
    Eurythmy: "Z"}

];
