module.exports = [
  {week:1,
    english:"# Easter (April 7-13) - PRIMAVERA\n\nWhen out of world-wide spaces\nThe sun speaks to the human mind,\nAnd gladness from the depths of soul\nBecomes, in seeing, one with light,\nThen rising from the sheath of self,\nThoughts soar to distances of space\nAnd dimly bind\nThe human being to the spirit's life.",
    italian:"# Atmosfera di Pasqua (7-13 Aprile)\n\nQuando da spazi universali il sole\nparla al senso dell'uomo\ne dal fondo dell'anima alla luce\nla gioia, contemplando, si congiunge,\nallor dal chiuso dell'egoità\nmigran pensieri nei lontani spazi\ne ottusamente avvincono\nallo spirito l'essere dell'uomo.",
    deutsch:"# Osterstimmung (7-13 April)\n\nWenn aus den Weltenweiten\nDie Sonne spricht zum Menschensinn\nUnd Freude aus den Seelentiefen\nDem Licht sich eint im Schauen,\nDann ziehen aus der Selbstheit Hülle\nGedanken in die Raumesfernen\nUnd binden dumpf\nDes Menschen Wesen an des Geistes Sein.",
    refweek: 52,
    Eurythmy: "A"},
  {week:2,
    english:"# Second Week (April 14-20)\n\nOut in the sense-world's glory\nThe power of thought gives up\nits separate being,\nAnd spirit worlds discover\nAgain their human offspring,\nWho germinates in them\nBut in itself must find\nThe fruit of soul.",
    italian:"# Seconda Settimana (14-20 Aprile)\n\nLà fuori, nel sensibile universo,\nsi smarrisce la forza del pensiero;\ni mondi dello spirito\nil rampollo ritrovano dell'uomo,\nche in essi il germe suo,\nma dell'anima il frutto\nin sé deve trovare.",
    deutsch:"# Zweite April-Woche (7.-13.April)\n\nIns Äußre des Sinnesalls\nVerliert Gedankenmacht ihr Eigensein;\nEs finden Geisteswelten\nDen Menschensprossen wieder,\nDer seinen Keim in ihnen,\nDoch seine Seelenfrucht\nIn sich muß finden.",
    refweek: 51,
    Eurythmy: "B"},
  {week:3, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:4, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:5, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:6, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:7, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:8, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:9, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:10, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:11, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:12, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:13, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:14,
    english:"# SUMMER Fourteenth Week (July 7-13)\n\nSurrendering to senses' revelation\nI lost the drive of my own being,\nAnd dreamlike thinking seemed\nTo daze and rob me of myself.\nYet quickening there draws near\nIn sense appearance cosmic thinking.",
    italian:"# ESTATE Quattordicesima settimana\n\nAl messaggio dei sensi m'abbandono,\ndell'esser mio lo stimolo ho perduto\nil sogno dei pensieri\npar che m'abbagli e mi rapisca il sé;\npur già, risvegliatore, a me s'accosta\nnell'illusione il cosmico pensiero.",
    deutsch:"# SOMMER Erste Juli-Woche\n\nAn Sinnesoffenbarung hingegeben\nVerlor ich Eigenwesens Trieb,\nGedankentraum, er schien\nBetäubend mir das Selbst zu rauben,\nDoch weckend nahet schon\nIm Sinnenschein mir Weltendenken.",
    refweek: 15,
    Eurythmy: "N"},
  {week:15, english:"# Fifteenth Week (July 14-20)\n\nI feel enchanted weaving\nOf spirit within outer glory.\nIn dullness of the senses\nIt has enwrapt my being\nIn order to bestow the strength\nWhich in its narrow bounds my I\nIs powerless to give itself.",
            italian:"#Quindicesima settimana\nCome incantato dentro le parvenze\ndello spirito io sento il lavorio;\nha nell'ottusità dei sensi avvolto\nla mia propria entità,\nper domarmi la forza\nche a se stessa d'infondere è impotente\nentro i limiti suoi l'egoità.",
            deutsch:"Ich fühle wie verzaubert\nIm Weltenschein des Geistes Weben:\nEs hat in Sinnesdumpfheit\nGehüllt mein Eigenwesen,\nZu schenken mir die Kraft:\nDie, ohnmächtig sich selbst zu geben,\nMein Ich in seinen Schranken ist.",
            refweek: 38,
            Eurythmy: "O"},
  {week:16, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:17, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:18, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:19, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:20, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:21, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:22, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:23, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:24, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:25, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:26, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:27, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:28, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:29, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:30, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:31, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:32, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:33, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:34, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:35, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:36, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:37, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:38,
    english:"# Christmas (December 22-28)\n\nThe spirit child within my soul\nI feel freed of enchantment.\nIn heart-high gladness has\n\
The holy cosmic Word engendered\nThe heavenly fruit of hope,\nWhich grows rejoicing into worlds afar\nOut of my being's godly roots.",
    italian:"# Atmosfera di Natale\n\nSento disincantato in grembo all'anima\nil figlio dello spritio;\nil sacrosanto verbo universale\ndel cuore ha generato nella luca\n- frutto celestiale - la speranza\nche dal fondo divino di me stesso\nentro gli spazi giubilando d'alza.",
    deutsch:"# Weihe-Nacht-Stimmung\n\nIch fühle wie entzaubert\nDas Geisteskind im Seelenschoss;\nEs hat in Herzenshelligkeit\nGezeugt das Heilige Weltenwort\nDer Hoffnung Himmelsfrucht,\nDie jubelnd wächst in Weltenfernen\nAus meines Wesens Gottesgrund.",
    refweek: 15,
    Eurythmy: "M"},
  {week:39,
    english:"# Thirty-ninth Week (December 29-January 4)\n\nSurrendering to spirit revelationI gain the light of cosmic being;\nThe power of thinking, growing clearer,\nGains strength to give myself to me,\nAnd quickening there frees itself\nFrom thinker's energy my sense of self.",
    italian:"# Trentanovesima settimana\n\nSe lo sguardo allo spirito rivolgo\nluce dell'ente universale acquisto.\nLa forza del pensiero ora s'accresce\nsé rischiandoper dar me a me stesso;\ne dalla possa del pensiero mio\n- risvegliatore -\nil sentimento del mio sé si leva",
    deutsch:"# Fünfte Dezember-Woche An\n\nGeistesoffenbarung hingegeben\nGewinne ich des Weltenwesens Licht.\nGedankenkraft, sie wächst\nSich klärend mir mich selbst zu geben,\nUnd weckend löst sich mir\nAus Denkermacht das Selbstgefühl.",
    refweek: 14,
    Eurythmy: "N"},
  {week:40, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:41, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:42, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:43, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:44, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:45, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:46, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:47, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:48, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:49, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:50, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:51,
    english:"# Fifty-first Week (March 23-29)\n\nInto our inner being\nThe riches of the senses pour.\nThe Cosmic Spirit finds itself\nReflected in the human eye,\bWhich ever must renew its strength\nFrom out that spirit source.",
    italian:"# Attesa di primavera\n\nEntro l'essere umano si riversa\ndei sensi la dovizia;\nsi rispecchia lo spirito del mondo\nnell'occhio umano,\nche trarn deve la sua forza nuova.",
    deutsch:"# Frühling-Erwartung (21.-25.März)\n\nIns Innre des Menschenwesens \nErgießt der Sinne Reichtum sich, \nEs findet sich der Weltengeist Im Spiegelbild des Menschenauges,\nDas seine Kraft aus ihm \nSich neu erschaffen muß.",
    refweek: 2,
    Eurythmy: ""},
  {week:52,
    english:"# Fifty-second Week (March 30)\n\nWhen from the depths of soul\nThe spirit turns to the life of worlds\nAnd beauty wells from wide expanses,\nThen out of heaven's distances\nStreams life-strength into human bodies,\nUniting by its mighty energy\nThe spirit's being with our human life.",
    italian:"# Cinquantaduesima settimana (30 Marzo)\n\nSe dal fondo dell'anima\nlo spirito si volge all'universo\ne bellezza fluisce dagli spazi,\nallor si versa da remoti cieli\nforza di vita negli umani corpi\ned operando con potenza unisce\nl'essenza dello spirito dell'uomo.",
    deutsch:"# Fünfte März-Woche\n\nWenn aus den Seelentiefen\nDer Geist sich wendet zu dem Weltensein\nUnd Schönheit quillt aus Raumesweiten,\nDann zieht aus Himmelsfernen\nDes Lebens Kraft in Menschenleiber\nUnd einet, machtvoll wirkend,\nDes Geistes Wesen mit dem Menschensein.",
    refweek: 1,
    Eurythmy: "Z"}

];
