module.exports = [
  {week:1,
    english:"# Easter (April 7-13) - PRIMAVERA\n\nWhen out of world-wide spaces\nThe sun speaks to the human mind,\nAnd gladness from the depths of soul\nBecomes, in seeing, one with light,\nThen rising from the sheath of self,\nThoughts soar to distances of space\nAnd dimly bind\nThe human being to the spirit's life.",
    italian:"# Atmosfera di Pasqua (7-13 Aprile)\n\nQuando da spazi universali il sole\nparla al senso dell'uomo\ne dal fondo dell'anima alla luce\nla gioia, contemplando, si congiunge,\nallor dal chiuso dell'egoità\nmigran pensieri nei lontani spazi\ne ottusamente avvincono\nallo spirito l'essere dell'uomo.",
    deutsch:"# Osterstimmung (7-13 April)\n\nWenn aus den Weltenweiten\nDie Sonne spricht zum Menschensinn\nUnd Freude aus den Seelentiefen\nDem Licht sich eint im Schauen,\nDann ziehen aus der Selbstheit Hülle\nGedanken in die Raumesfernen\nUnd binden dumpf\nDes Menschen Wesen an des Geistes Sein.",
    refweek: 52,
    Eurythmy: "A"},
  {week:2,
    english:"# Second Week (April 14-20)\n\nOut in the sense-world's glory\nThe power of thought gives up\nits separate being,\nAnd spirit worlds discover\nAgain their human offspring,\nWho germinates in them\nBut in itself must find\nThe fruit of soul.",
    italian:"# Seconda Settimana (14-20 Aprile)\n\nLà fuori, nel sensibile universo,\nsi smarrisce la forza del pensiero;\ni mondi dello spirito\nil rampollo ritrovano dell'uomo,\nche in essi il germe suo,\nma dell'anima il frutto\nin sé deve trovare.",
    deutsch:"# Zweite April-Woche (7.-13.April)\n\nIns Äußre des Sinnesalls\nVerliert Gedankenmacht ihr Eigensein;\nEs finden Geisteswelten\nDen Menschensprossen wieder,\nDer seinen Keim in ihnen,\nDoch seine Seelenfrucht\nIn sich muß finden.",
    refweek: 51,
    Eurythmy: "B"},
  {week:3,
    english:"# Third Week (April 21-27)\n\nThus to the World-All speaks,\nIn self-forgetfulness\nAnd mindful of its primal state,\nThe growing human I:\nIn you, if I can free myself\nFrom fetters of my selfhood,\nI fathom my essential being.",
    italian:"# Terza Settimana (21-27 Aprile)\n\nAll'universo parla, dimentico di sé\ne del suo stato originario memore,\ncrescendo l'io dell'uomo:\nin te, sciogliendomi dai ceppi\ndi ciò che mi è particolare, scopro\nil vero essere mio.",
    deutsch:"# Dritte und vierte April-Woche (14.-24. April)\n\nEs spricht zum Weltenall,\nSich selbst vergessend\nUnd seines Urstands eingedenk,\nDes Menschen wachsend Ich:\nIn dir, befreiend mich\nAus meiner Eigenheiten Fessel,\nErgründe ich mein echtes Wesen.",
    refweek: 50,
    Eurythmy: "C"},
  {week:4,
    english:"# Fourth Week (April 28-May 4)\n\nI sense a kindred nature to my own:\nThus speaks perceptive feeling\nAs in the sun-illuminated world\nIt merges with the floods of light;\nTo thinking's clarity\nMy feeling would give warmth\nAnd firmly bind as one\nThe human being and the world.",
    italian:"# Quarta settimana (28 Aprile - 4 Maggio)\n\nIo sento l'entità dell'esser mio:\ncosì mi parla il senso\nche nel mondo dal sole illuminato\nai fiotti della luce si coingiunge;\nvuole al pensiero\noltre alla chiarità donar calore\ne uomo e mondo\navvincer strettamente in unità.",
    deutsch:"# Vierte April-Woche bis erste Mai-Woche (25. April-4. Mai)\n\nIch fühle Wesen meines Wesens: \nSo spricht Empfindung,\nDie in der sonnerhellten Welt \nMit Lichtesfluten sich vereint; \nSie will dem Denken \nZur Klarheit Wärme schenken \nUnd Mensch und Welt \nIn Einheit fest verbinden.",
    refweek: 49,
    Eurythmy: "D"},
  {week:5,
    english:"# Fifth Week (May 5-11)\n\nWithin the light that out of spirit depths\nWeaves germinating power into space\nAnd manifests the gods' creative work:\nWithin its shine, the soul's true being\nIs widened into worldwide life\nAnd resurrected\nFrom narrow selfhood's inner power.",
    italian:"# Quinta settimana\n\nEntro la luce\nche da profondità spirituali\ncol lavorio fecondo nello spazio\nmanifesta il creare degli dèi,\nora l'anima appare\na vita uniiversale dilatata\ne dalla chiusa forza\nrisorta dell'angusta egoità.",
    deutsch:"# Erste Mai-Woche (5.-11. Mai)\n\nIm Lichte, das aus Geistestiefen \nIm Raume fruchtbar webend \nDer Götter Schaffen offenbart: \nIn ihm erscheint der Seele Wesen \nGeweitet zu dem Weltensein \nUnd auferstanden \nAus enger Selbstheit Innenmacht.",
    refweek: 48,
    Eurythmy: "E"},
  {week:6,
    english:"# Sixth Week (May 12-18)\n\nThere has arisen from its narrow limits\nMy self and finds itself\nAs revelation of all worlds\nWithin the sway of time and space;\nThe world, as archetype divine,\nDisplays to me at every turn\nThe truth of my own likeness.",
    italian:"# Sesta settimana \n\nDa vita singola è il mio sé risorto\ned entro all'universo or si palesa\nnelle forze del tempo e dello spazio;\nin ogni luogo il mondo mi rivela\n - l'archetipo divino -\ndell'immagine mia la verità.",
    deutsch:"# Zweite Mai-Woche (12.-18.Mai)\n\nEs ist erstanden aus der Eigenheit\nMein Selbst und findet sich\nAls Weltenoffenbarung\nIn Zeit- und Raumeskräften;\nDie Welt, sie zeigt mir überall\nAls göttlich Urbild\nDes eignen Abbilds Wahrheit",
    refweek: 47,
    Eurythmy: "F"},
  {week:7,
    english:"# Seventh Week (May 19-25)\n\nMy self is threatening to fly forth,\nLured strongly by the world's enticing light.\nCome forth, prophetic feeling,\nTake up with strength your rightful task:\nReplace in me the power of thought\nWhich in the senses' glory\nWould gladly lose itself.",
    italian:"# Settima settimana (19 Maggio - 25 Maggio)\n\nIl sé minanccia di sfuggiarmi\nda immensa luce ardentemente attratto.\nOr entra, mio presagio,\ncon ogni potestà nei tuoi diritti,\nsuppliscimi la forza del pensiero\nche dai sensi abbagliato\nse stessso perder vuole.",
    deutsch:"# Dritte Mai-Woche (19.-25.Mai)\n\nMein Selbst, es drohet zu entfliehen, \nVom Weltenlichte mächtig angezogen. \nNun trete du mein Ahnen \nIn deine Rechte kräftig ein, \nErsetze mir des Denkens Macht, \nDas in der Sinne Schein \nSich selbst verlieren will.",
    refweek: 46,
    Eurythmy: "G"},
  {week:8,
    english:"# Eighth Week (May 26-June 1)\n\nThe senses' might grows strong \nUnited with the gods' creative work;\nIt presses down my power of thinking\nInto a dreamlike dullness.\nWhen godly being\nDesires union with my soul,\nMust human thinking\nIn quiet dream-life rest content.",
    italian:"# Ottava settimana (26 Maggio - 1 Giugno)\n\nOr s'accresce dei sensi la potenza\nin lega col creare degli dèi;\nla forza del pensiero\na ottuso sogno mi riduce.\nSe natura divina\nvuole al mio cuore unirsi,\numilmente l'umano mio pensiero\ndeve a vita sognante ritirarsi.",
    deutsch:"# Vierte Mai-Woche (20.-31.Mai)\n\nEs wächst der Sinne Macht\nIm Bunde mit der Götter Schaffen,\nSie drückt des Denkens Kraft\nZur Traumes Dumpfheit mir herab.\nWenn göttlich Wesen\nSich meiner Seele einen will,\nMuß menschlich Denken\nIm Traumessein sich still bescheiden.",
    refweek: 45,
    Eurythmy: "H"},
  {week:9,
    english:"# Ninth Week (June 2-8)\n\nWhen I forget the narrow will of self,\nThe cosmic warmth that heralds summer's glory\nFills all my soul and spirit;\nTo lose myself in light\nIs the command of spirit vision\nAnd intuition tells me strongly:\nO lose yourself to find yourself.",
    deutsch:"# Erste Juni-Woche (1.-8. Juni)\n\nVergessend meine Willenseigenheit, \nErfüllet Weltenwärme sommerkündend \nMir Geist und Seelenwesen; \nIm Licht mich zu verlieren \nGebietet mir das Geistesschauen, \nUnd kraftvoll kündet Ahnung mir: \nVerliere dich, um dich zu finden.",
    italian:"# Nona settimana (Giugno 2-8)\n\nNunzio d'estate un cosmico calore\ndel mio volere immemore\nor lo spirito e l'anima mi colma;\nsmarrirmi nella luce\nm'impone l'occhio mio spirituale\ne possente m'annuncia il mio presagio\nperder tidevi, per trovar te stesso.",
    refweek: 44,
    Eurythmy: "I"},
  {week:10,
    english:"# Tenth Week (June 9-15)\n\nTo summer's radiant heights\nThe sun in shining majesty ascends;\nIt takes my human feeling\nInto its own wide realms of space.\nWithin my inner being stirs\nPresentiment which heralds dimly,\nYou shall in future know:\nA godly being now has touched you.",
    italian:"# Decima settimana (Giugno 9-15)\n\nA estive altezze\nlucente s'alza l'essere del sole,\ne il mio sentiero umano\nporta con sé nei suoi remoti spazi;\ns'agita in me preago\nun senso e ottuso annuncia:\nun gioro tu saprai\nche or t'ha sentito un essere divino.",
    deutsch:"# Zweite Juni-Woche (9.-15. Juni)\n\nZu sommerlichen HöhenErhebt der Sonne leuchtend Wesen sich; \nEs nimmt mein menschlich Fühlen \nIn seine Raumesweiten mit. \nErahnend regt im Innern sich \nEmpfindung, dumpf mir kündend, \nErkennen wirst du einst: \nDich fühlte jetzt ein Gotteswesen.",
    refweek: 43,
    Eurythmy: "K"},
  {week:11,
    english:"# Eleventh Week (June 16-23)\n\nIn this the sun's high hour it rests\nWith you to understand these words of wisdom:\nSurrender to the beauty of the world,\nBe stirred with new-enlivened feeling;\nThe human I can lose itself\nAnd find itself within the cosmic I.",
    italian:"# Undicesima settimana (Giugno 16-23)\n\nIn quest'ora solare a te s'addice\nd'interpretare il saggio ammonimento:\ndel mondo alla bellezza abbondonato,\nin te sentendo te sperimentare:\npuò l'io dell'uomo perdersi\ne ritrovarsi dentro l'io del mondo.",
    deutsch:"# Dritte Juni-Woche (16.-22.Juni)\n\nEs ist in dieser Sonnenstunde \nAn dir, die weise Kunde zu erkennen: \nAn Weltenschönheit hingegeben, \nIn dir dich fühlend zu durchleben: \nVerlieren kann das Menschen-Ich \nUnd finden sich im Welten-Ich.",
    refweek: 42,
    Eurythmy: "L"},
  {week:12,
    english:"# St. John's Tide (June 24)\n\nThe radiant beauty of the world\nCompels my inmost soul to free\nGod-given powers of my nature\nThat they may soar into the cosmos,\nTo take wing from myself\nAnd trustingly to seek myself\nIn cosmic light and cosmic warmth.",
    italian:"# Atmosfera di San Giovanni (25 giugno)\n\nLo splendore lucente del creato\ndal profondo del cuor mi costringe\na dar libero volo\ndella mia vita alle divine forze;\na abbandonar me stesso\neppur fidente a ricercarmi\nnella luce e nel calore del mondo.",
    deutsch:"# Johanni-Stimmung (23.-29. Juni)\n\nDer Welten Schönheitsglanz, \nEr zwinget mich aus Seelentiefen \nDes Eigenlebens Götterkräfte \nZum Weltenfluge zu entbinden; \nMich selber zu verlassen, \nVertrauend nur mich suchend \nIn Weltenlicht und Weltenwärme.",
    refweek: 41,
    Eurythmy: "M"},
  {week:13,
    english:"# Thirteenth Week (June 30-July 6)\n\nAnd when I live in senses' heights,\nThere flames up deep within my soul\nOut of the spirit's fiery worlds\nThe gods' own word of truth:\nIn spirit sources seek expectantly\nTo find your spirit kinship.",
    italian:"# Tedicesima settimana\n\nE quando sono all'apice dei sensi\nfiammeggia in fondo al cuore\nda mondi dello spirito infocati\nil mondo dvino:\npresago cerca nel profondo spirito\nallo spirito affine di trovarti.",
    deutsch:"# Fünfte Juni-Woche bis erste Juli-Woche\n\nUnd bin ich in den Sinneshöhen, So flammt in meinen Seelentiefen \nAus Geistes Feuerwelten \nDer Götter Wahrheitswort: \nIn Geistesgründen suche ahnend \nDich geistverwandt zu finden.",
    refweek: 15,
    Eurythmy: "M"},
  {week:14,
    english:"# SUMMER Fourteenth Week (July 7-13)\n\nSurrendering to senses' revelation\nI lost the drive of my own being,\nAnd dreamlike thinking seemed\nTo daze and rob me of myself.\nYet quickening there draws near\nIn sense appearance cosmic thinking.",
    italian:"# ESTATE Quattordicesima settimana\n\nAl messaggio dei sensi m'abbandono,\ndell'esser mio lo stimolo ho perduto\nil sogno dei pensieri\npar che m'abbagli e mi rapisca il sé;\npur già, risvegliatore, a me s'accosta\nnell'illusione il cosmico pensiero.",
    deutsch:"# SOMMER Erste Juli-Woche\n\nAn Sinnesoffenbarung hingegeben\nVerlor ich Eigenwesens Trieb,\nGedankentraum, er schien\nBetäubend mir das Selbst zu rauben,\nDoch weckend nahet schon\nIm Sinnenschein mir Weltendenken.",
    refweek: 15,
    Eurythmy: "N"},
  {week:15, english:"# Fifteenth Week (July 14-20)\n\nI feel enchanted weaving\nOf spirit within outer glory.\nIn dullness of the senses\nIt has enwrapt my being\nIn order to bestow the strength\nWhich in its narrow bounds my I\nIs powerless to give itself.",
            italian:"#Quindicesima settimana\nCome incantato dentro le parvenze\ndello spirito io sento il lavorio;\nha nell'ottusità dei sensi avvolto\nla mia propria entità,\nper domarmi la forza\nche a se stessa d'infondere è impotente\nentro i limiti suoi l'egoità.",
            deutsch:"Ich fühle wie verzaubert\nIm Weltenschein des Geistes Weben:\nEs hat in Sinnesdumpfheit\nGehüllt mein Eigenwesen,\nZu schenken mir die Kraft:\nDie, ohnmächtig sich selbst zu geben,\nMein Ich in seinen Schranken ist.",
            refweek: 38,
            Eurythmy: "O"},
  {week:16, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:17, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:18, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:19, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:20, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:21, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:22, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:23, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:24, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:25, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:26, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:27, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:28, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:29, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:30, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:31, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:32, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:33, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:34, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:35, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:36, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:37, english:"week1", italian:"settimana1", deutsch:"woche1", refweek: 15},
  {week:38,
    english:"# Christmas (December 22-28)\n\nThe spirit child within my soul\nI feel freed of enchantment.\nIn heart-high gladness has\n\
The holy cosmic Word engendered\nThe heavenly fruit of hope,\nWhich grows rejoicing into worlds afar\nOut of my being's godly roots.",
    italian:"# Atmosfera di Natale\n\nSento disincantato in grembo all'anima\nil figlio dello spritio;\nil sacrosanto verbo universale\ndel cuore ha generato nella luca\n- frutto celestiale - la speranza\nche dal fondo divino di me stesso\nentro gli spazi giubilando d'alza.",
    deutsch:"# Weihe-Nacht-Stimmung\n\nIch fühle wie entzaubert\nDas Geisteskind im Seelenschoss;\nEs hat in Herzenshelligkeit\nGezeugt das Heilige Weltenwort\nDer Hoffnung Himmelsfrucht,\nDie jubelnd wächst in Weltenfernen\nAus meines Wesens Gottesgrund.",
    refweek: 15,
    Eurythmy: "M"},
  {week:39,
    english:"# Thirty-ninth Week (December 29-January 4)\n\nSurrendering to spirit revelationI gain the light of cosmic being;\nThe power of thinking, growing clearer,\nGains strength to give myself to me,\nAnd quickening there frees itself\nFrom thinker's energy my sense of self.",
    italian:"# Trentanovesima settimana\n\nSe lo sguardo allo spirito rivolgo\nluce dell'ente universale acquisto.\nLa forza del pensiero ora s'accresce\nsé rischiandoper dar me a me stesso;\ne dalla possa del pensiero mio\n- risvegliatore -\nil sentimento del mio sé si leva",
    deutsch:"# Fünfte Dezember-Woche An\n\nGeistesoffenbarung hingegeben\nGewinne ich des Weltenwesens Licht.\nGedankenkraft, sie wächst\nSich klärend mir mich selbst zu geben,\nUnd weckend löst sich mir\nAus Denkermacht das Selbstgefühl.",
    refweek: 14,
    Eurythmy: "N"},
  {week:40,
    english:"# Fortieth Week (January 5-11)\n\nAnd when I live in spirit depths\nAnd dwell within my soul's foundations,\nThere streams from love-worlds of the heart,\nTo fill the vain delusion of the self,\nThe fiery power of the cosmic Word.",
    italian:"# Quarantesima settimana\n\nE quando entro lo spirito m'immergo,\nmi s'empie in fondo all'anima,\ndall'amoroso mondo del mio cuore,\nil vuoto sogno del particolare\ncon la fiamma del verbo universale.",
    deutsch:"# Erste Januar-Woche\n\nUnd bin ich in den Geistestiefen,\nErfüllt in meinen Seelengründen\nAus Herzens Liebewelten\nDer Eigenheiten leerer Wahn\n Sich mit des Weltenwortes Feuerkraft.",
    refweek: 13,
    Eurythmy: "O"},
  {week:41,
    english:"# Forty-first Week (January 12-18)\n\nThe soul's creative might\nStrives outward from the heart's own core\nTo kindle and inflame god-given powers\nIn human life to right activity;\nThe soul thus shapes itself\nIn human loving and in human working.",
    italian:"# Quarantunesima settimana (Gennaio 12-18)\n\nDel cuore la potenza creatrice\nprofondamente anela\nforze divine nella vita umana\nad infiammare per un retto agire,\na plasmare se stessa\nnell'amore e nella opera dell'uomo.",
    deutsch:"# Zweite Januar-Woche\n\nDer Seele Schaffensmacht,\nSie strebet aus dem Herzensgrunde,\nIm Menschenleben Götterkräfte\nZu rechtem Wirken zu entflammen,\nSich selber zu gestalten\nIn Menschenliebe und im Menschenwerke.",
    refweek: 12,
    Eurythmy: "P"},
  {week:42,
    english:"# Forty-second Week (January 19-25)\n\nIn this the shrouding gloom of winterThe soul feels ardently impelled\nTo manifest its innate strength,\nTo guide itself to realms of darkness,\nAnticipating thus\nThrough warmth of heart the sense-world's\nrevelation.\n",
    italian:"# Quarantaduesima settimana (Gennaio 19-25)\n\nIn questo oscuro inverno\nè potente dell'anima l'impulso\na palesare la sua proprietà forza,\nad aprirle un cammino nelle tenebre\ne a presagire col calor del cuore\ndei sensi la rivelazione.",
    deutsch:"# Dritte Januar-Woche (19.-25.Januar)\n\nEs ist in diesem Winterdunkel\nDie Offenbarung eigner Kraft\nDer Seele starker Trieb,\nIn Finsternisse sie zu lenken\nUnd ahnend vorzufühlen,\nDurch Herzenswärme, Sinnesoffenbarung.",
    refweek: 11,
    Eurythmy: "Q"},
  {week:43,
    english:"# Forty-third Week (January 26-February 1)\n\nIn winter's depths is kindled\nTrue spirit life with glowing warmth;\nIt gives to world appearance,\nThrough forces of the heart, the power to be.\nGrown strong, the human soul defies\nWith inner fire the coldness of the world.",
    italian:"# Quaranduesima settimana (26 Gennaio - 1 Febbraio)\n\nNel più profondo inverno\nla spiritualità vera d'accende;\ncon le forze del cuore\nda alla parvenza potestà di vita;\ns'oppone al gelo cosmico e s'accresce\ndell'anima la fiamma dentro l'uomo.",
    deutsch:"# Vierte Januar-Woche (26.Januar-1.Februar)\n\nIn winterlichen Tiefen\nErwarmt des Geistes wahres Sein;\nEs gibt dem Weltenscheine\nDurch Herzenskräfte Daseinsmächte;\nDer Weltenkälte trotzt erstarkend\nDas Seelenfeuer im Menscheninnern.",
    refweek: 10,
    Eurythmy: "R"},
  {week:44,
    english:"# Forty-fourth Week (February 2-8)\n\nIn reaching for new sense attractions,\nSoul-clarity would fill,\nMindful of spirit-birth attained,\nThe world's bewildering, sprouting growth\nWith the creative will of my own thinking. ",
    italian:"# Quarantaquattresima settimana (2-8 Febbraio)\n\nCogliendo nuovi stimoli dei sensi\nla chiarità dell'anima ch'è memore\ndel generato spirito,\nriempie l'universo in divenire,\nin tutto il suo caostico rigoglio,\ncol mio pensiero che a creare anela.",
    deutsch:"# Erste Februar-Woche (2.-8.Februar)\n\nErgreifend neue Sinnesreize \nErfüllet Seelenklarheit, \nEingedenk vollzogner Geistgeburt, \nVerwirrend sprossend Weltenwerden \nMit meines Denkens Schöpferwillen.",
    refweek: 9,
    Eurythmy: "S"},
  {week:45,
    english:"# Forty-fifth Week (February 9-15)\n\nMy power of thought grows firm\nUnited with the spirit's birth.\nIt lifts the senses' dull attractions\nTo bright-lit clarity.\nWhen soul-abundance\nDesires union with the world's becoming,\nMust senses' revelation\nReceive the light of thinking.",
    italian:"# Quantacinquesima settimana (9 Febbraio - 15 Febbraio)\n\nLa forza del pensiero si rinsalda\nal nasce dello spirito congiiunta;\ngli ottusi stimoli dei sensi\nsolleva a chiarità.\nSe la pienezza d'anima\nal divenire vuol del mondo unirsi,\ndei sensi la rivelazione\nla luce deve accoglier del pensiero.",
    deutsch:"# Zweite Februar-Woche (9.-15.Februar)\n\nEs festigt sich Gedankenmacht \nIm Bunde mit der Geistgeburt, \nSie hellt der Sinne dumpfe Reize \nZur vollen Klarheit auf. \nWenn Seelenfülle\nSich mit dem Weltenwerden einen will, \nMuß Sinnesoffenbarung \nDes Denkens Licht empfangen.",
    refweek: 8,
    Eurythmy: "T"},
  {week:46,
    english:"# Forty-sixth Week (February 16-22)\n\nThe world is threatening to stun\nThe inborn forces of my soul;\nNow, memory, come forth\nFrom spirit depths, enkindling light;\nInvigorate my inward sight\nWhich only by the strength of will\nIs able to sustain itself.",
    italian:"# Quantaseiesima settimana (16 Febbraio - 22 Febbraio)\n\nIl mondo ora minaccia di stordire\ndell'anima la forza innata;\nor sorgi tu, ricordo,\ndal fondo dello spritio, splendente,\ne la veggenza accrescimi\nche solo può sussistere\nmercé la forza della volontà.",
    deutsch:"# Dritte Februar-Woche (16. -22.Februar)\n\nDie Welt, sie drohet zu betäuben \nDer Seele eingebor'ne Kraft; \nNun trete du, Erinnerung, \nAus Geistestiefen leuchtend auf \nUnd stärke mir das Schauen, \nDas nur durch Willenskräfte \nSich selbst erhalten kann.",
    refweek: 7,
    Eurythmy: "U"},
  {week:47,
    english:"# Forty-seventh Week (February 23-March 1)\n\nThere will arise out of the world's great womb,\nQuickening the senses' life, the joy of growth.\nNow may it find my strength of thought\nWell armed by powers divine\nWhich strongly live within my being.",
    italian:"# Quarantasettesima settimana ( 23 Febbraio - 1 Marzo)\n\n Risorger vuol dal grembo universale,\ndei sensi ravvivando la parvenza,\ngioia del divenire.\nTrovi il pensiero mio fortificato\ndalle forze divine\nche vigorose vivono entro di me",
    deutsch:"# Vierte Februar-Woche (23.Februar-1.März)\n\nEs will erstehen aus dem Weltenschoße, \nDen Sinnenschein erquickend, Werdelust. \nSie finde meines Denkens Kraft \nGerüstet durch die Gotteskräfte, \nDie kräftig mir im Innern leben.",
    refweek: 6,
    Eurythmy: "V"},
  {week:48,
    english:"# Forty-eighth Week (March 2-8)\n\nWithin the light that out of world-wide heights\nWould stream with power toward the soul,\nMay certainty of cosmic thinking\nArise to solve the soul's enigmas —\nAnd focusing its mighty rays,\nAwaken love in human hearts.",
    italian:"# Quarantottesima settimana (2-8 Marzo)\n\nEntro la luce che possentemente\nvuol dai cieli nell'anima fluire,\nappaia, enigmi d'anima sciogliendo,\nsicurezza del scosmico pensiero\ne dei suoi raggi la potenza aduni \ndestando amore nell'umano cuore",
    deutsch:"# Erste März-Woche (2.-8.März)\n\nIm Lichte, das aus Weltenhöhen\nDer Seele machtvoll fließen will, \nErscheine, lösend Seelenrätsel, \nDes Weltendenkens Sicherheit, \nVersammelnd seiner Strahlen Macht, \nIm Menschenherzen Liebe weckend.",
    refweek: 5,
    Eurythmy: "W"},
  {week:49,
    english:"# Forty-ninth Week (March 9-15)\n\nI feel the force of cosmic life:\nThus speaks my clarity of thought,\nRecalling its own spirit growth\nThrough nights of cosmic darkness,\nAnd to the new approach of cosmic day\nIt turns its inward rays of hope.",
    italian:"# Quarantanovesima settimana (9-15 Marzo)\n\nDell'universo in me sento la forza:\ncosì parla chiarezza di pensiero;\nrammenta del suo spirito il fiorire\nnelle notturne tenebre del mondo,\ne raggi di speranza entro di sé\nprotende al giorno cosmico che viene.",
    deutsch:"# Zweite März-Woche (9.-15.März)\n\nIch fühle Kraft des Weltenseins: \nSo spricht Gedankenklarheit, \nGedenkend eignen Geistes Wachsen \nIn finstern Weltennächten, \nUnd neigt dem nahen Weltentage \nDes Innern Hoffnungsstrahlen.",
    refweek: 4,
    Eurythmy: "X"},
  {week:50,
    english:"# Fiftieth Week (March 16-22)\n\nThus to the human ego speaks\nIn mighty revelation,\nUnfolding its inherent powers,\nThe joy of growth throughout the world:\nI carry into you my life\nFrom its enchanted bondage\nAnd so attain my truest goal.",
    italian:"# Cinquantesima settimana\n\nAll'io dell'uomo parla,\npossente rivelandosi\ne dell'essere suo sciogliendo forze,\ngioiosamente il cosmo in divenire:\ntrasportando entro te la vita mia\ndal magico suo regno,\nla vera meta io attingo.",
    deutsch:"# Dritte März-Woche (16.-20.März)\n\nEs spricht zum Menschen-Ich, \nSich machtvoll offenbarend \nUnd seines Wesens Kräfte lösend, \nDes Weltendaseins Werdelust: \nIn dich mein Leben tragend \nAus seinem Zauberbanne, \nErreiche ich mein wahres Ziel.",
    refweek: 3,
    Eurythmy: "Y"},
  {week:51,
    english:"# Fifty-first Week (March 23-29)\n\nInto our inner being\nThe riches of the senses pour.\nThe Cosmic Spirit finds itself\nReflected in the human eye,\bWhich ever must renew its strength\nFrom out that spirit source.",
    italian:"# Attesa di primavera\n\nEntro l'essere umano si riversa\ndei sensi la dovizia;\nsi rispecchia lo spirito del mondo\nnell'occhio umano,\nche trarn deve la sua forza nuova.",
    deutsch:"# Frühling-Erwartung (21.-25.März)\n\nIns Innre des Menschenwesens \nErgießt der Sinne Reichtum sich, \nEs findet sich der Weltengeist Im Spiegelbild des Menschenauges,\nDas seine Kraft aus ihm \nSich neu erschaffen muß.",
    refweek: 2,
    Eurythmy: ""},
  {week:52,
    english:"# Fifty-second Week (March 30)\n\nWhen from the depths of soul\nThe spirit turns to the life of worlds\nAnd beauty wells from wide expanses,\nThen out of heaven's distances\nStreams life-strength into human bodies,\nUniting by its mighty energy\nThe spirit's being with our human life.",
    italian:"# Cinquantaduesima settimana (30 Marzo)\n\nSe dal fondo dell'anima\nlo spirito si volge all'universo\ne bellezza fluisce dagli spazi,\nallor si versa da remoti cieli\nforza di vita negli umani corpi\ned operando con potenza unisce\nl'essenza dello spirito dell'uomo.",
    deutsch:"# Fünfte März-Woche\n\nWenn aus den Seelentiefen\nDer Geist sich wendet zu dem Weltensein\nUnd Schönheit quillt aus Raumesweiten,\nDann zieht aus Himmelsfernen\nDes Lebens Kraft in Menschenleiber\nUnd einet, machtvoll wirkend,\nDes Geistes Wesen mit dem Menschensein.",
    refweek: 1,
    Eurythmy: "Z"}

];
